/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSavingsRouteImport } from './routes/_app.savings'
import { Route as AppReportRouteImport } from './routes/_app.report'
import { Route as AppPayoffRouteImport } from './routes/_app.payoff'
import { Route as AppIncomeRouteImport } from './routes/_app.income'
import { Route as AppChartsRouteImport } from './routes/_app.charts'
import { Route as AppCardsRouteImport } from './routes/_app.cards'
import { Route as AppCalendarRouteImport } from './routes/_app.calendar'
import { Route as AppBudgetRouteImport } from './routes/_app.budget'
import { Route as AppBillsRouteImport } from './routes/_app.bills'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSavingsRoute = AppSavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportRoute = AppReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AppRoute,
} as any)
const AppPayoffRoute = AppPayoffRouteImport.update({
  id: '/payoff',
  path: '/payoff',
  getParentRoute: () => AppRoute,
} as any)
const AppIncomeRoute = AppIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => AppRoute,
} as any)
const AppChartsRoute = AppChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => AppRoute,
} as any)
const AppCardsRoute = AppCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetRoute = AppBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => AppRoute,
} as any)
const AppBillsRoute = AppBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/bills': typeof AppBillsRoute
  '/budget': typeof AppBudgetRoute
  '/calendar': typeof AppCalendarRoute
  '/cards': typeof AppCardsRoute
  '/charts': typeof AppChartsRoute
  '/income': typeof AppIncomeRoute
  '/payoff': typeof AppPayoffRoute
  '/report': typeof AppReportRoute
  '/savings': typeof AppSavingsRoute
  '/settings': typeof AppSettingsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/bills': typeof AppBillsRoute
  '/budget': typeof AppBudgetRoute
  '/calendar': typeof AppCalendarRoute
  '/cards': typeof AppCardsRoute
  '/charts': typeof AppChartsRoute
  '/income': typeof AppIncomeRoute
  '/payoff': typeof AppPayoffRoute
  '/report': typeof AppReportRoute
  '/savings': typeof AppSavingsRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/bills': typeof AppBillsRoute
  '/_app/budget': typeof AppBudgetRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/cards': typeof AppCardsRoute
  '/_app/charts': typeof AppChartsRoute
  '/_app/income': typeof AppIncomeRoute
  '/_app/payoff': typeof AppPayoffRoute
  '/_app/report': typeof AppReportRoute
  '/_app/savings': typeof AppSavingsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/bills'
    | '/budget'
    | '/calendar'
    | '/cards'
    | '/charts'
    | '/income'
    | '/payoff'
    | '/report'
    | '/savings'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/bills'
    | '/budget'
    | '/calendar'
    | '/cards'
    | '/charts'
    | '/income'
    | '/payoff'
    | '/report'
    | '/savings'
    | '/settings'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/bills'
    | '/_app/budget'
    | '/_app/calendar'
    | '/_app/cards'
    | '/_app/charts'
    | '/_app/income'
    | '/_app/payoff'
    | '/_app/report'
    | '/_app/savings'
    | '/_app/settings'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/savings': {
      id: '/_app/savings'
      path: '/savings'
      fullPath: '/savings'
      preLoaderRoute: typeof AppSavingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/report': {
      id: '/_app/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AppReportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payoff': {
      id: '/_app/payoff'
      path: '/payoff'
      fullPath: '/payoff'
      preLoaderRoute: typeof AppPayoffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/income': {
      id: '/_app/income'
      path: '/income'
      fullPath: '/income'
      preLoaderRoute: typeof AppIncomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/charts': {
      id: '/_app/charts'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof AppChartsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cards': {
      id: '/_app/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof AppCardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/budget': {
      id: '/_app/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof AppBudgetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bills': {
      id: '/_app/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof AppBillsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBillsRoute: typeof AppBillsRoute
  AppBudgetRoute: typeof AppBudgetRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppCardsRoute: typeof AppCardsRoute
  AppChartsRoute: typeof AppChartsRoute
  AppIncomeRoute: typeof AppIncomeRoute
  AppPayoffRoute: typeof AppPayoffRoute
  AppReportRoute: typeof AppReportRoute
  AppSavingsRoute: typeof AppSavingsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBillsRoute: AppBillsRoute,
  AppBudgetRoute: AppBudgetRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppCardsRoute: AppCardsRoute,
  AppChartsRoute: AppChartsRoute,
  AppIncomeRoute: AppIncomeRoute,
  AppPayoffRoute: AppPayoffRoute,
  AppReportRoute: AppReportRoute,
  AppSavingsRoute: AppSavingsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
